tls_server_config:
  # Certificate and key files for server to use to authenticate to client.
  cert_file: /tmp/i2acerts/server.cer
  key_file: /tmp/i2acerts/server.key

# Usernames and hashed passwords that have full access to the web
# server via basic authentication. If empty, no basic authentication is
# required. Passwords are hashed with bcrypt.
basic_auth_users:
  ${PROMETHEUS_USERNAME}: ${PROMETHEUS_PASSWORD}
