tls_server_config:
  # Certificate and key files for server to use to authenticate to client.
  cert_file: /tmp/i2acerts/server.cer
  key_file: /tmp/i2acerts/server.key

  # Server policy for client authentication. Maps to ClientAuth Policies.
  # For more detail on clientAuth options:
  # https://golang.org/pkg/crypto/tls/#ClientAuthType
  #
  # NOTE: If you want to enable client authentication, you need to use
  # RequireAndVerifyClientCert. Other values are insecure.
  client_auth_type: VerifyClientCertIfGiven

  # CA certificate for client certificate authentication to the server.
  client_ca_file: /tmp/i2acerts/CA.cer

# Usernames and hashed passwords that have full access to the web
# server via basic authentication. If empty, no basic authentication is
# required. Passwords are hashed with bcrypt.
basic_auth_users:
  ${PROMETHEUS_USERNAME}: ${PROMETHEUS_PASSWORD}
